name: Run Vitest

on:
  push:
    branches: [ '**' ]
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Enable corepack
      run: corepack enable

    - name: Install dependencies
      run: pnpm ci

    - name: Run Vitest(test)
      run: pnpm run test
