name: Build and Deploy
on:
  push:
    paths: ["src/**", "src/stories/**"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install -g pnpm
          pnpm install
          pnpm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.STORYBOOK_TOKEN }}
          BRANCH: edge
          FOLDER: docs-build
          # CLEAN: true
          TARGET_FOLDER: docs
          BUILD_SCRIPT: pnpm install && pnpm run build-storybook
